Handle backlashes and dollar signs in captured groups
With a start section defined with a capturing group such as:

  ^>>>: Start: (.*)

And a section name referring to the captured group using curly braces
such as: `{1}`

Then, when the group contains a backslash (\) or a dollar sign ($):

  >>> Start: cp --verbose $WORKSPACE/src/LocalSettings.php $LOG_DIR

It throws:

  java.lang.IllegalArgumentException: Illegal group reference

The reason is `String.replaceAll(regex, replacement)` threats
backslashes and dollars in `replacement` specially. The `$` is used to
refer to a captured group.

Quote replacement strings in the group.

Bug: https://phabricator.wikimedia.org/T420347